CREATE TABLE NecroWiKi.EXAMPLE_DATABASE (
	ID INT auto_increment NOT NULL,
	NAME varchar(100) NULL,
	CONSTRAINT EXAMPLE_DATABASE_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;